

name: CI

on:
  push:
    branches: [ master ]
 


jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Installing Nodejs
      uses: action/setup-node@v2-beta
      with:
        node-version: 12 
    - name: Installing surge
      run: npm install -g surge
    - name: Running surge
      run: surge ./ syedusamanaveed.surge.sh --token ${{secrets.SURGE_TOKEN}}
 
